CREATE TABLE PRODUTOS (
	ID INTEGER NOT NULL,
	PARTNUMBER VARCHAR(20),
	DESCRICAO VARCHAR(100),
	ATIVO char(1),
	CONSTRAINT INTEG_2 PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX RDB$PRIMARY1 ON PRODUTOS (ID);

CREATE SEQUENCE sq_produto;

CREATE OR ALTER TRIGGER trProdutos
BEFORE INSERT 
POSITION 0
ON PRODUTOS
AS
BEGIN
    NEW.id = NEXT VALUE FOR sq_produto;
END